=== pombredanne/maven-license-plugin-1/license-manager-core/src/main/resources/com/mycila/license/core/type/document-types.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://mycila.com/license/mappings/1.0" xmlns="http://mycila.com/license/mappings/1.0">

    <xs:element name="mappings">
        <xs:annotation>
            <xs:documentation source="version">1.0+</xs:documentation>
            <xs:documentation source="description">
                Root element of all mapping definitions
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="document" type="Document" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="id">
            <xs:selector xpath=".//*"/>
            <xs:field xpath="@extension"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="Document">
        <xs:annotation>
            <xs:documentation source="version">1.0+</xs:documentation>
            <xs:documentation source="description">
                Define a mapping between an extension (file type) and a header style
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="extension" type="Extension" use="required"/>
        <xs:attribute name="style" type="Style" use="required"/>
    </xs:complexType>

    <xs:simpleType name="Extension">
        <xs:annotation>
            <xs:documentation source="version">1.0+</xs:documentation>
            <xs:documentation source="description">
                The extension of the document
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Style">
        <xs:annotation>
            <xs:documentation source="version">1.0+</xs:documentation>
            <xs:documentation source="description">
                The header style
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z_][a-z0-9_]*"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== pombredanne/maven-license-plugin-1/license-manager-core/src/main/resources/com/mycila/license/core/type/default-document-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings xmlns="http://mycila.com/license/mappings/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://mycila.com/license/mappings/1.0 document-types.xsd">

    <document extension="java" style="javadoc"/>
    <document extension="groovy" style="javadoc"/>
    <document extension="js" style="slashstar"/>
    <document extension="css" style="javadoc"/>
    <document extension="cs" style="javadoc"/>
    <document extension="as" style="javadoc"/>
    <document extension="c" style="javadoc"/>
    <document extension="cpp" style="javadoc"/>
    <document extension="h" style="javadoc"/>
    <document extension="xml" style="xml"/>
    <document extension="xhtml" style="xml"/>
    <document extension="dtd" style="xml"/>
    <document extension="xsd" style="xml"/>
    <document extension="fml" style="xml"/>
    <document extension="xsl" style="xml"/>
    <document extension="html" style="xml"/>
    <document extension="htm" style="xml"/>
    <document extension="jspx" style="xml"/>
    <document extension="apt" style="doubletilde"/>
    <document extension="properties" style="script"/>
    <document extension="sh" style="script"/>
    <document extension="py" style="script"/>
    <document extension="rb" style="script"/>
    <document extension="pl" style="script"/>
    <document extension="pm" style="script"/>
    <document extension="txt" style="text"/>
    <document extension="bat" style="batch"/>
    <document extension="cmd" style="batch"/>
    <document extension="sql" style="doubledashes"/>
    <document extension="adb" style="doubledashes"/>
    <document extension="ads" style="doubledashes"/>
    <document extension="e" style="doubledashes"/>
    <document extension="jsp" style="dynascript"/>
    <document extension="asp" style="asp"/>
    <document extension="php" style="php"/>
    <document extension="vm" style="sharpstart"/>
    <document extension="ftl" style="ftl"/>
    <document extension="asm" style="semicolon"/>
    <document extension="cfc" style="dynascript3"/>
    <document extension="cfm" style="dynascript3"/>
    <document extension="pas" style="bracesstar"/>
    <document extension="erl" style="percent3"/>
    <document extension="hrl" style="percent3"/>
    <document extension="f" style="exclamation"/>
    <document extension="el" style="exclamation3"/>
    <document extension="lua" style="lua"/>
    <document extension="bas" style="apostrophe"/>
    <document extension="mxml" style="xml"/>
    <document extension="aj" style="javadoc"/>
    <document extension="pom" style="xml"/>
    
</mappings>
